name: expense_tracker
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.11
  google_sign_in: ^6.3.0
  flutter_svg: ^2.2.0
  animated_custom_dropdown: ^3.1.1
  flutter_animate: ^4.5.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.2.2


  lottie: ^3.2.0
  get: ^4.7.2
  # firebase_core: ^3.15.1
  # google_sign_in: ^7.1.0
  # firebase_auth: ^5.6.2
  # sign_in_with_apple: ^7.0.1
  #setting
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.2
  sign_in_with_apple: ^7.0.1
  


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/expense_category_items/
    - assets/file_svgs/
    - assets/expense_monthly_svgs/


